version: '3.8'

services:
  app:
    build:
      context: ./site
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./site:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  node_modules: